# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'ExampleCustomUISwitch' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'CustomUISwitch', :path => "/Users/llovretic/Desktop/Posao/FACTORY/CustomUISwitch"
  # Pods for ExampleCustomUISwitch

end
