# Uncomment the next line to define a global platform for your project

source 'http://git.plavatvornica.com/factory/iOS/podspec.git'

target 'ExampleCustomUISwitch' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  #pod 'CustomUISwitch', :path => "/Users/llovretic/Desktop/CustomUISwitch"
  pod 'CustomUISwitch'
  # Pods for ExampleCustomUISwitch

end
